# Generated by Django 4.0.1 on 2022-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('typ', models.TextField(blank=True)),
                ('col', models.CharField(choices=[('manager', 'Manager'), ('role', 'ROLE')], default='manager', max_length=8)),
                ('text', models.CharField(max_length=8)),
            ],
        ),
    ]
