# Generated by Django 4.0.1 on 2022-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailtemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('manager', 'Manager'), ('role', 'ROLE')], default='manager', max_length=8)),
                ('CC', models.EmailField(max_length=70)),
                ('reply', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=100)),
                ('emailbody', models.TextField(blank=True)),
            ],
        ),
    ]
